#!/bin/sh
gnome-terminal -x bash -c 'roscore'
sleep 2
gnome-terminal -x bash -c "roslaunch turtlebot_arm_controller controller.launch"
sleep 2
gnome-terminal -x bash -c "roslaunch astra_launch astra.launch"
sleep 2
gnome-terminal -x bash -c "roslaunch turtlebot_arm_kinect_calibration calibrate_node_only.launch"

# torque off
rosservice call /arm_shoulder_pan_joint/torque_enable false
rosservice call /arm_shoulder_lift_joint/torque_enable false
rosservice call /arm_elbow_flex_joint/torque_enable false
rosservice call /arm_wrist_flex_joint/torque_enable false
rosservice call /gripper_joint/torque_enable false



